T: 20
checkpoint_selection_metric: AIC
dataset: survival
dropout:
  percentage_drop: 0
dropout_method: null
experiment:
  debug: 'True'
  log_path: logs
  name: experiment_surv_1
experiment_dir: !!python/object/apply:pathlib.PosixPath
- logs
- experiment_surv_1
local_port: 8081
metrics_aggregation: weighted_average
min_available_clients: 2
min_evaluate_clients: 2
min_fit_clients: 2
model: cox
n_features: 0
neural_network:
  device: cpu
  dropout_p: 0.2
  local_epochs: 100
num_clients: 2
num_rounds: 5
production_mode: 'False'
random_forest:
  balanced_rf: 'true'
sandbox_path: ./sandbox
smoothWeights:
  smoothing_strenght: 0.5
smooth_method: EqualVoting
strategy: FedAvg
target_label: null
train_labels: null
weighted_random_forest:
  balanced_rf: 'true'
  levelOfDetail: DecisionTree
